version: '2'

services:
  integration-test:
    build: .
    depends_on:
      - hello-world
      - redis
  hello-world:
    build: ..
    environment: 
      - REDIS_SERVICE_HOST=redis
    ports: 
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: redis
